- glossary-api.sln
- src/NCI.OCPL.Api.Glossary/Controllers/TermController.cs
- src/NCI.OCPL.Api.Glossary/NCI.OCPL.Api.Glossary.csproj
- src/NCI.OCPL.Api.Glossary/Program.cs
- src/NCI.OCPL.Api.Glossary/Startup.cs
- src/NCI.OCPL.Api.Glossary/appsettings.json
- test/NCI.OCPL.Api.Glossary.Tests/NCI.OCPL.Api.Glossary.Tests.csproj
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermControllerTest.cs
Changes as part of initial project setup includes
1. creating src and test project
2. creating glossary-api.sln file
3. creating TermController and its unit test
4. adding swagger documentation
> #1 Create Initial API Solution

- src/NCI.OCPL.Api.Glossary/Controllers/TermController.cs
- src/NCI.OCPL.Api.Glossary/Exception/APIErrorException.cs
- src/NCI.OCPL.Api.Glossary/Models/AudienceType.cs
- src/NCI.OCPL.Api.Glossary/Models/Definition.cs
- src/NCI.OCPL.Api.Glossary/Models/GlossaryTerm.cs
- src/NCI.OCPL.Api.Glossary/Models/IMedia.cs
- src/NCI.OCPL.Api.Glossary/Models/MediaType.cs
- src/NCI.OCPL.Api.Glossary/Models/Pronounciation.cs
- src/NCI.OCPL.Api.Glossary/Models/RelatedResourceType.cs
- test/NCI.OCPL.Api.Glossary.Tests/NCI.OCPL.Api.Glossary.Tests.csproj
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermControllerTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestData/TestData.json
The new endpoint will be /glossary/v1/term/{dictionary}/{audience}/{language}/{id}
1. Modified TermController to add a new method to correspond to the
url
2. Addition of new Model classes to support the new endpoint
3. Amendment to Testcase
Closes #3
>   NCIOCPL #3 Create getGlossaryTerm endpoint

- src/NCI.OCPL.Api.Glossary/Controllers/TermController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Interfaces/ITermsQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/TermQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/TermsQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TestData_SearchForTerms.json
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermControllerTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTests.cs
1. Addition of new search method in Controller and Service Layer
2. Addition of test cases for the new method
Closes #15
> (#15) Create the SearchTerms endpoint

- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Interfaces/ITermsQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/TermsQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTests.cs
1. Addition of new expand method in TermsController and Service Layer
2. Addition of test cases for the new method
Closes(#16)
> (#16) Create the Expand Terms endpoint

- src/NCI.OCPL.Api.Glossary/Controllers/AutosuggestController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Interfaces/IAutosuggestQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/AutosuggestQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/TermsQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/AutosuggestControllerTest.cs
(#18) Create the Autosuggest endpoint
1. Addition of new autosuggest method in AutosuggestController and
Service Layer
2. Addition of test cases for the new method
3. Stubbed out version of AutosuggestQueryService
>  (#17) Create Autosuggest controller and service

- src/NCI.OCPL.Api.Glossary/Models/Options/GlossaryAPIOptions.cs
- src/NCI.OCPL.Api.Glossary/Startup.cs
- src/NCI.OCPL.Api.Glossary/appsettings.json
Common infrastructure for retrieving API options into services.
> Add GlossaryAPIOptions (shared infrastructure)

- test/NCI.OCPL.Api.Glossary.Tests/TestData/ESTermQueryData/TermQuery.json
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/ArrayComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/GlossaryTermComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermQueryServiceTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermQueryServiceTestObjects/BaseTermQueryTestData.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermQueryServiceTestObjects/ESTermQueryServiceTestData.cs
1. Created new test cases for GetById
2. Created additional files required to run the test cases
Closes #21
> (#21) Unit Tests for TermQueryService::GetById

- src/NCI.OCPL.Api.Glossary/Models/Image.cs
- src/NCI.OCPL.Api.Glossary/Models/ImageSource.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/ImageComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/ImageSourceComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermQueryServiceTestObjects/TermScenario_44058_VideoExernalLink.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermQueryServiceTestObjects/TermScenario_445043_ImageAndExternalLink.cs
- Holds image file source uris
- Implemented tests
Closes #64
> (#64) Implemented ImageSource property

- src/NCI.OCPL.Api.Glossary/Controllers/AutosuggestController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Models/AudienceType.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/AutosuggestControllerTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTests.cs
> (#71) Change TermController::GetById() use string for audience argument.

- src/NCI.OCPL.Api.Glossary/Controllers/AutosuggestController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTests.cs
- AutosuggestController::GetSuggestions()
- TermsController::GetAll()
Closes #74
> (#74) Fix controller routes

- src/NCI.OCPL.Api.Glossary/Models/GlossaryTerm.cs
- src/NCI.OCPL.Api.Glossary/Models/TermOtherLanguage.cs
- test/NCI.OCPL.Api.Glossary.Tests/TestData/ESTermsQueryData/GetById/44058_cancer.gov_en_patient.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_Expand.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_GetById_WithTranslation.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_GetByName.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_GetWithFallback_GeneticsHP.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_GetWithFallback_TermsPatient.json
- test/NCI.OCPL.Api.Glossary.Tests/TestData/TermsControllerData/TestData_SearchForTerms.json
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/GlossaryTermComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Models/TermOtherLanguageComparer.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/GetById/GetById_44058_VideoExernalLink.cs
- Updated model with translation link
- Created comparer TermOtherLanguage and updated GlossaryTermComparer
to support OtherLanguages
- Updated tests
> (#99) Support Translation Link

- src/NCI.OCPL.Api.Common/NCI.OCPL.Api.Common.csproj
- src/NCI.OCPL.Api.Common/NciStartupBase.cs
- src/NCI.OCPL.Api.Glossary/NCI.OCPL.Api.Glossary.csproj
> (#90) Updated NSwag to v13.2.2

- src/NCI.OCPL.Api.Common/NciStartupBase.cs
> (#113) Set basepath for swagger documents.

- .github/workflows/workflow.yml
> (#115) Publish the src/NCI.OCPL.Api.Glossary/ project.

- .github/workflows/workflow.yml
> (#121) Create build-info.json.

- integration-tests/README.md
- integration-tests/data/source/glossary-es-mapping.json
- integration-tests/features/autosuggest/success-begins-genetics-healthprof-en-gene.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-en-car.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-en-cel.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-en-node-biopsy.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-en-two-thirds.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-es-crónica.json
- integration-tests/features/autosuggest/success-contains-cgov-patient-es-two-thirds.json
- integration-tests/features/autosuggest/success-contains-genetics-healthprof-en-variant.json
- integration-tests/features/autosuggest/success.feature
- integration-tests/features/terms/search/success-contains-cgov-patient-en-two-thirds.json
- integration-tests/features/terms/search/success-contains-cgov-patient-es-two-thirds.json
- integration-tests/features/terms/search/success.feature
- src/NCI.OCPL.Api.Glossary/Controllers/AutosuggestController.cs
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Services/ESAutosuggestQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_CGov_Contains_Ablacion_Spanish_Patient.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_CGov_Contains_Cat_English_Patient.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_Genetics_Contains_Gene_English_HealthProfessional.cs
Spaces in term name (#118)
Path separator in term name (#125)
Close #118 
Close #125
> Handle term name edge cases

- integration-tests/features/terms/search/search-begins-exact-match-mev-linear.json
- integration-tests/features/terms/search/search-contains-cgov-patient-en-two-thirds.json
- integration-tests/features/terms/search/search-contains-cgov-patient-es-two-thirds.json
- integration-tests/features/terms/search/search-contains-exact-match-mev-linear.json
- integration-tests/features/terms/search/search-exact-cgov-patient-en-greek-char.json
- integration-tests/features/terms/search/search-exact-cgov-patient-en-one-word.json
- integration-tests/features/terms/search/search-exact-cgov-patient-en-square-bracket.json
- integration-tests/features/terms/search/search-exact-cgov-patient-en-with-slash.json
- integration-tests/features/terms/search/search-exact-cgov-patient-es-with-space.json
- integration-tests/features/terms/search/search-exact-cgov-patient-es-with-spanish-char.json
- src/NCI.OCPL.Api.Glossary/Controllers/TermsController.cs
- src/NCI.OCPL.Api.Glossary/Interfaces/ITermsQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/ESTermsQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTest.Expand.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTest.GetAll.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/TermsControllerTest.Search.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.Expand.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.GetAll.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.Search.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/Expand/ExpandRequestAdditionalInfo.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/Expand/ExpandRequestBase.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/Expand/ExpandRequestDefaultFields.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/GetAll/GetAll_Request_AdditionalFields.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/GetAll/GetAll_Request_Base.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/GetAll/GetAll_Request_DefaultFields.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/Search/Terms_Search_Request_Begins.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESTermsQueryServiceTestObjects/Search/Terms_Search_Request_Exact.cs
> implement includeAdditionalInformation

- src/NCI.OCPL.Api.Glossary/web.config
> (#134) Allow 'bin' as a path component.

- .github/workflows/workflow.yml
- integration-tests/data/source/glossary-es-mapping.json
- integration-tests/docker-glossary-api/docker-compose.yml
- src/NCI.OCPL.Api.Glossary/Models/GlossaryTerm.cs
- src/NCI.OCPL.Api.Glossary/NCI.OCPL.Api.Glossary.csproj
- src/NCI.OCPL.Api.Glossary/Program.cs
- src/NCI.OCPL.Api.Glossary/Services/ESAutosuggestQueryService.cs
- src/NCI.OCPL.Api.Glossary/Services/ESTermsQueryService.cs
- test/NCI.OCPL.Api.Glossary.Tests/NCI.OCPL.Api.Glossary.Tests.csproj
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESAutosuggestQueryServiceResponseTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESAutosuggestQueryServiceTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.Expand.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.GetAll.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.GetById.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.GetByName.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQueryServiceTest.Search.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Services/ESTermsQuery_CountTest.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_CGov_Contains_Ablacion_Spanish_Patient.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_CGov_Contains_Cat_English_Patient.cs
- test/NCI.OCPL.Api.Glossary.Tests/Tests/TestDataObjects/ESAutosuggestRequestTestObjects/Autosuggest_Request_Genetics_Contains_Gene_English_HealthProfessional.cs
Closes #147 
Closes #151 
Closes #152 
Closes #154 
Closes #156 
Closes #157 
Closes #158 
Closes #153
> Multiple tickets: Upgrade Glossary API to Elasticsearch 7.9

- .editorconfig
- .github/workflows/workflow.yml
- integration-tests/docker-glossary-api/api/Dockerfile
- integration-tests/features/healthcheck/status.feature
- src/NCI.OCPL.Api.Glossary/Controllers/HealthCheckController.cs
- src/NCI.OCPL.Api.Glossary/NCI.OCPL.Api.Glossary.csproj
- src/NCI.OCPL.Api.Glossary/Startup.cs
- test/NCI.OCPL.Api.Glossary.Tests/NCI.OCPL.Api.Glossary.Tests.csproj
- test/NCI.OCPL.Api.Glossary.Tests/Tests/Controllers/HealthCheckControllerTests.cs
Closes #172
Closes #174 
Closes #155
> (#172) Update to .Net 6.
